### ISSUE TITLE
not working with 3.7.x

### ISSUE THREAD

**Issue by chandu0101** [nonara/ts-patch#1]
```
 ts-patch check
Checking TypeScript v3.7.1-rc installation in ../node_modules/typescript

[+] tsc.js is patched with ts-patch version 1.0.2.
[+] tsserverlibrary.js is patched with ts-patch version 1.0.2.
[+] typescript.js is patched with ts-patch version 1.0.2.
[+] typescriptServices.js is patched with ts-patch version 1.0.2.
```
tsc Build failing 

```
import { transformer } from "./transformer"
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginCreator.resolveFactory (/node_modules/typescript/lib/tsc.js:133432:34)
    at PluginCreator.createTransformers (/typescript/lib/tsc.js:133398:36)
    at Object.newEmit [as emit] (/node_modules/typescript/lib/tsc.js:133553:52)
    at Object.getFileEmitOutput (node_modules/typescript/lib/tsc.js:97281:34)
error Command failed with exit code 1.
```
when i uninstall build working fine with tsc.

**Comment by nonara** [comment]
This sounds like it might not be calling registering ts-node register during the createProgram routine.

Can you go into your package directory and run `npm list` and paste the full output please?

**Comment by chandu0101** [comment]
Package.json 
```
  "devDependencies": {
    "ttypescript": "^1.5.7",
    "@types/node": "^12.7.12",
    "ts-node": "^8.4.1",
    "typescript": "^3.7.1-rc"
  }
```

NPM List :  
```
├── @types/node@12.11.7
├─┬ ts-node@8.4.1
│ ├── arg@4.1.1
│ ├── diff@4.0.1
│ ├── make-error@1.3.5
│ ├─┬ source-map-support@0.5.15
│ │ ├── buffer-from@1.1.1
│ │ └── source-map@0.6.1
│ └── yn@3.1.1
├─┬ ttypescript@1.5.7
│ └─┬ resolve@1.12.0
│   └── path-parse@1.0.6
└─┬ UNMET PEER DEPENDENCY typescript@3.7.1-rc
  ├── ts-node@8.4.1 deduped
  └── UNMET PEER DEPENDENCY typescript@>=2.0

npm ERR! peer dep missing: typescript@>=2.0, required by ts-node@8.4.1
npm ERR! peer dep missing: typescript@^3.2.2, required by ttypescript@1.5.7
```

**Comment by nonara** [comment]
Are you sure that's the full result from npm list? I don't see typescript in the list.

Can you also show me your project structure and npm version?

I've just checked 3.7.1-rc thoroughly and confirmed that it does work with ts-patch.

**Comment by chandu0101** [comment]
cool thank you :)

**Comment by nonara** [comment]
I've addressed a few issues which I think should cover your case also. Would you mind updating to 1.0.4 and letting me know if it's resolved, please?

**Comment by chandu0101** [comment]
working perfect, thanks alot 👍
