### ISSUE TITLE
Bug: Typescript compiler errors show up as ts-patch ESM errors in 3.0.1

### ISSUE THREAD

**Issue by Griffork** [nonara/ts-patch#111]
Loving the new update!

Certain compiler errors seem to show up as the following:
```
         npm run build
         
         > common@0.0.0 build
         > tsc --build tsconfig.json
         
         C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:428
                                 throw e;
                                 ^
         
         TsPatchError: Plugin is an ESM module. To enable experimental ESM support, install the 'esm' package as a (dev)-dependency or global.
             at getEsmLibrary (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:62:27)
             at Module.wrappedRequire (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:130:37)
             at require (node:internal/modules/cjs/helpers:110:18)
             at loadPlugin (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:413:27)
             at Object.resolveFactory (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:391:40)
             at PluginCreator.createTransformers (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:237:49)
             at Object.newEmit [as emit] (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:515:52)
             at emitNextAffectedFile (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:121489:36)
             at Object.emit (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:121610:39)
             at emitFilesAndReportErrors (C:\Sources\Project\Common\node_modules\typescript\lib\tsc.js:123215:101) {
           diagnostic: undefined
         }
```

Caused by:

``` typescript
//include.ts:
export function Type_Ext(version: string) {
    return "Hello World";
}

//index.ts:
import { Type_Ext } from "./include.js";
export import Type = Type_Ext;
```
Actual TSC Error (when ts-patch is uninstalled):
```
TS2503: Cannot find namespace 'Type_Ext'.
```

I know it's not my plugin because my plugin works fine when the error is fixed.

**Comment by Griffork** [comment]
My bad, I forgot to run with the --force flag. It's actually happening all the time. It'd be nice to know which file is the cause.

**Comment by nonara** [comment]
Hello! That error happens when your plugin's entry file is detected by TS (or specified explicitly via the isESM option) to be ESM.

It should only throw if require throws an error stating that it can't require the file because it's ESM.

Assuming it is ESM, as the error states, you can add the esm library as a dependency.

**Comment by Griffork** [comment]
I have figured it out, this was entirely my fault. Sorry for the bother nonara!

New library updates are going really well btw.
